"""empty message

Revision ID: 913327cbd27f
Revises: 6766785dafd1
Create Date: 2019-10-07 12:21:08.560870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913327cbd27f'
down_revision = '6766785dafd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255)))
    op.execute('UPDATE users SET password=email')
    op.alter_column('users', 'password', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
